### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by E-Silverstein** [E-Silverstein/CS546-Group-11-Final-Project#2]
# Admin Dashboard 
Lets start figuring out how everything interacts on the full stack by starting with the admin dashboard. It should provide a good way to be able to test all the database functionalities along with starting authentication and integration with front end. Here's what we should do to start and feel free to add if I forgot anything. 
* Setup database to support assigning users to be an admin 
* Setup routing to enable authentication and routes to the proper admin dashboard pages
* Create a prototype front end for sign up and sign in
* Create a prototype front end along with templating for displaying the proper data in the admin dashboard (users, posts, comments, keywords, reports) along with the data's respective attributes

**Comment by 21dhruvp** [comment]
Splitting these to different issues as needed.
